# Generated by Django 2.0.2 on 2018-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elysium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
